site_name: Kiyarash's CTF Writeups
site_url: https://kiyarash.github.io/
site_description: CTF Writeups by Kiyarash
site_author: Kiyarash

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: light green
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: material/flag
    repo: fontawesome/brands/github
  features:
    - header.autohide
    - navigation.tabs
    - navigation.footer

repo_url: https://github.com/KiyarashFarahani/writeups
repo_name: KiyarashFarahani/writeups


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KiyarashFarahani
      name: GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/KiyarashNF
      name: Telegram
  

      
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

